
export const PATHS = {
  // Public auth
  SPLASH: "/",
  ROLE_SELECT: "/role-select",
  LOGIN: "/login",
  OTP: "/otp",
  COMING_SOON: "/coming-soon",

  // Onboarding Student
  CREATE_PROFILE: "/create-profile",
  SUBJECT_SELECTION: "/subject-selection",
  LEARNING_PLAN: "/learning-plan",
  COUPON: "/coupon",
  PLAN_SCREEN: "/plan-screen",
  PAYMENT_FAILED: "/payment-failed",

  // Student tabs (StudentLayout)
  STUDENT_DASHBOARD: "/student-dashboard",
  ASK_DOUBT: "/ask-doubt",
  MCQ: "/mcq",
  LIVE_CLASSES: "/live-classes",
  PROFILE: "/profile",

  //Teacher Flow
  TEACHER_REGISTRATION:"/teacher-registration",
  QUALIFICATION_DETAILS:"/qualification-details",
  BASICPROFILE_DETAILS:"/basicprofile-details",
  EXPERIENCE_DETAILS:"/experience-details",
  //TEACHERSUBJECT_SELECTION:"/subject-selection",
  TEACHERCLASS_SELECTION:"/teacherclass-selection",
  CLASS_SELECTION:"/class-selection",
  BOARDSELECTION_CARD:"/board-selection",
  LANGUAGAE_SELECTION:"/language-selection",
  DOCUMENT_UPLOAD:"/document-upload",
  INTERVIEW_SCHEDULING:"/interview-scheduling",
  VIDEO_DEMO:"/video-demo",
  PROFILE_REVIEW:"/profile-review",
  INTERVIEW_CONFIRM:"/interview-confirm",
  VERIFICATION_STATUS:"/verify-status",
  APPLICATION_REJECTED:"/application-rejected",
  TEACHER_DASHBOARD:"/teacher-dashboard",
  AVAILABILITY_STATUS:"/availability-status",
  SLOT_AVAILABLILITY:"/slot-availability",
  REQUEST_NOTIFICATION:"/request-notification",
  TEACHER_SESSION:"/teacher-session",
  SESSION_WARNING:"/session-warning",
  RESOLVE_DOUBT:"/resolve-doubt",
  AUDIO_CALLINITIIATED:"/audio-call",
  TEACHERLIVE_SESSION:"/live-session",
  WHITEBOARD_SESSION:"/white-board",
  RECORDING_LIBRARY:"/recording-library",
  LIVE_CLASS:"/live-class",
  LIVECLASS_REQUEST:"/class-request",
  //TEACHERREFERRAL_HISTORY:"/teachreferral-history",
  SESSION_COMPLETION:"/session-completion",
  TEACHER_NOTIFICATION:"/teacher-notification",
  HELP_CENTRE:"/help-centre",
  SUPPORT_TICKET:"/support-ticket",
  TICKET_DETAILS:"/ticket-details",
  TEACHERSESSION_HISTORY:"/teachersession-history",
  SESSION_DEATILS:"/session-details",
  PERFORMANCE_ANALYTICS:"/performance-analytics",
  REQUEST:"/request",
  ACCOUNT_STATUS:"/account-status",
  ACCOUNT_BLOCKED:"/account-blocked",
  CONNECTION_LOST:"/connection-lost",
  REVIEW_STATUS:"/review-status",
  UPLOAD_ERROR:"/upload-error",
  SESSION_INTERRUPTION:"/session-interrupt",
  WITHDRAWAL_PROCESSING:"/withdrawl-processing",
  WITHDRAWAL_FAILED:"/withdrawal-failed",
  REFERRAL_CREDITED:"/referral-credit",
  INVALID_REFERRAL:"/invalid-referral",
  APPLICATION_STATUS:"/application-status",
  RECORDING_PROCESSING:"/recording-processing",
  TEACHERDASH_BOARD:"teacher-dashboard",
  TEACHER_LOGIN:"/teacher-login",
  CHAT_SESSION:"chat-session",
  TEACHERTICKET_DETAILS:"/ticket-details",
  SESSSION_HISTORY:"/session-history",
  REQUEST_PAGE:"request-page",
  //WITHDRAWAL_PROCESS:"/withdrawal-process",




  // Student flows
  VIDEO_UPLOAD: "/video-upload",
  DOUBT_SUBMITTED: "/doubt-submitted",
  AUDIO_CALL: "/audio-call",
  LIVE_SESSION: "/live-session",
  SHORT_LIVE_SESSION: "/short-live-session",
  SESSION_FEEDBACK: "/session-feedback",
  SESSION_HISTORY: "/session-history",
  SPINNER: "/spinner",
  REFER_EARN: "/refer-earn",
  REFERRAL_HISTORY: "/referral-history",
  REFERRAL_REWARD: "/referral-reward",
  PLAN_UPGRADE: "/plan-upgrade",

  // Legacy
  DASHBOARD: "/dashboard",
} as const;

export type AppPath = (typeof PATHS)[keyof typeof PATHS];
